import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideHeader from "@/app/Component/SideHeader";
import Header from "@/app/Component/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col items-center">
            {children}
          </div>
          <SideHeader />
        </div>
      </body>
    </html>
  );
}
